FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /auth ./cmd/main.go

FROM alpine:3.20
COPY --from=builder /auth /auth
EXPOSE 50051
CMD ["/auth"]
