// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/content/content.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddContentRequest) Reset() {
	*x = AddContentRequest{}
	mi := &file_proto_content_content_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContentRequest) ProtoMessage() {}

func (x *AddContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_content_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContentRequest.ProtoReflect.Descriptor instead.
func (*AddContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_content_proto_rawDescGZIP(), []int{0}
}

func (x *AddContentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddContentRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *AddContentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddContentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_proto_content_content_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_content_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_proto_content_content_proto_rawDescGZIP(), []int{1}
}

func (x *Content) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Content) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Content) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Content) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Content) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Content) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Content) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Content) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type AddContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *Content               `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddContentResponse) Reset() {
	*x = AddContentResponse{}
	mi := &file_proto_content_content_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddContentResponse) ProtoMessage() {}

func (x *AddContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_content_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddContentResponse.ProtoReflect.Descriptor instead.
func (*AddContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_content_proto_rawDescGZIP(), []int{2}
}

func (x *AddContentResponse) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetContentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentsRequest) Reset() {
	*x = GetContentsRequest{}
	mi := &file_proto_content_content_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentsRequest) ProtoMessage() {}

func (x *GetContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_content_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentsRequest.ProtoReflect.Descriptor instead.
func (*GetContentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_content_proto_rawDescGZIP(), []int{3}
}

func (x *GetContentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetContentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*Content             `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentsResponse) Reset() {
	*x = GetContentsResponse{}
	mi := &file_proto_content_content_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentsResponse) ProtoMessage() {}

func (x *GetContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_content_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentsResponse.ProtoReflect.Descriptor instead.
func (*GetContentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_content_proto_rawDescGZIP(), []int{4}
}

func (x *GetContentsResponse) GetContents() []*Content {
	if x != nil {
		return x.Contents
	}
	return nil
}

type DeleteContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContentRequest) Reset() {
	*x = DeleteContentRequest{}
	mi := &file_proto_content_content_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentRequest) ProtoMessage() {}

func (x *DeleteContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_content_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentRequest.ProtoReflect.Descriptor instead.
func (*DeleteContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_content_content_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteContentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteContentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContentResponse) Reset() {
	*x = DeleteContentResponse{}
	mi := &file_proto_content_content_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContentResponse) ProtoMessage() {}

func (x *DeleteContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_content_content_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContentResponse.ProtoReflect.Descriptor instead.
func (*DeleteContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_content_content_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteContentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_content_content_proto protoreflect.FileDescriptor

const file_proto_content_content_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/content/content.proto\x12\acontent\"}\n" +
	"\x11AddContentRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12 \n" +
	"\vcontentType\x18\x02 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"\xdf\x01\n" +
	"\aContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12 \n" +
	"\vcontentType\x18\x03 \x01(\tR\vcontentType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bimageUrl\x18\x06 \x01(\tR\bimageUrl\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x1c\n" +
	"\tcreatedAt\x18\b \x01(\x03R\tcreatedAt\"@\n" +
	"\x12AddContentResponse\x12*\n" +
	"\acontent\x18\x01 \x01(\v2\x10.content.ContentR\acontent\",\n" +
	"\x12GetContentsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"C\n" +
	"\x13GetContentsResponse\x12,\n" +
	"\bcontents\x18\x01 \x03(\v2\x10.content.ContentR\bcontents\">\n" +
	"\x14DeleteContentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"1\n" +
	"\x15DeleteContentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf1\x01\n" +
	"\x0eContentService\x12E\n" +
	"\n" +
	"AddContent\x12\x1a.content.AddContentRequest\x1a\x1b.content.AddContentResponse\x12H\n" +
	"\vGetContents\x12\x1b.content.GetContentsRequest\x1a\x1c.content.GetContentsResponse\x12N\n" +
	"\rDeleteContent\x12\x1d.content.DeleteContentRequest\x1a\x1e.content.DeleteContentResponseB8Z6github.com/jram17/second-brain/services/content/pkg/pbb\x06proto3"

var (
	file_proto_content_content_proto_rawDescOnce sync.Once
	file_proto_content_content_proto_rawDescData []byte
)

func file_proto_content_content_proto_rawDescGZIP() []byte {
	file_proto_content_content_proto_rawDescOnce.Do(func() {
		file_proto_content_content_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_content_content_proto_rawDesc), len(file_proto_content_content_proto_rawDesc)))
	})
	return file_proto_content_content_proto_rawDescData
}

var file_proto_content_content_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_content_content_proto_goTypes = []any{
	(*AddContentRequest)(nil),     // 0: content.AddContentRequest
	(*Content)(nil),               // 1: content.Content
	(*AddContentResponse)(nil),    // 2: content.AddContentResponse
	(*GetContentsRequest)(nil),    // 3: content.GetContentsRequest
	(*GetContentsResponse)(nil),   // 4: content.GetContentsResponse
	(*DeleteContentRequest)(nil),  // 5: content.DeleteContentRequest
	(*DeleteContentResponse)(nil), // 6: content.DeleteContentResponse
}
var file_proto_content_content_proto_depIdxs = []int32{
	1, // 0: content.AddContentResponse.content:type_name -> content.Content
	1, // 1: content.GetContentsResponse.contents:type_name -> content.Content
	0, // 2: content.ContentService.AddContent:input_type -> content.AddContentRequest
	3, // 3: content.ContentService.GetContents:input_type -> content.GetContentsRequest
	5, // 4: content.ContentService.DeleteContent:input_type -> content.DeleteContentRequest
	2, // 5: content.ContentService.AddContent:output_type -> content.AddContentResponse
	4, // 6: content.ContentService.GetContents:output_type -> content.GetContentsResponse
	6, // 7: content.ContentService.DeleteContent:output_type -> content.DeleteContentResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_content_content_proto_init() }
func file_proto_content_content_proto_init() {
	if File_proto_content_content_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_content_content_proto_rawDesc), len(file_proto_content_content_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_content_content_proto_goTypes,
		DependencyIndexes: file_proto_content_content_proto_depIdxs,
		MessageInfos:      file_proto_content_content_proto_msgTypes,
	}.Build()
	File_proto_content_content_proto = out.File
	file_proto_content_content_proto_goTypes = nil
	file_proto_content_content_proto_depIdxs = nil
}
